on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Each job runs in fresh VM, so checkout is needed
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Run tests
        run: ./mvnw test
      
      - name: Run integration tests
        run: ./mvnw verify
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.ECR_REGISTRY }}/myapp:latest
            ${{ secrets.ECR_REGISTRY }}/myapp:${{ github.sha }}
        # Ensure you've set secrets: ECR_REGISTRY=123456789012.dkr.ecr.us-west-2.amazonaws.com
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      
      - name: Deploy to ECS
        run: |
          # Update ECS service with new image (requires AWS CLI v2+)
          aws ecs update-service \
            --cluster production-cluster \
            --service app-service \
            --force-new-deployment
          
          aws ecs wait services-stable \
            --cluster production-cluster \
            --services app-service